#ifndef __EVENTS_ENUM_H__
#define __EVENTS_ENUM_H__

enum event_enum {
    SPACE_BAR_PRESSED,
    ESCAPE_PRESSED,
    RIGHT_PRESSED,
    LEFT_PRESSED,
    RIGHT_UNPRESSED,
    LEFT_UNPRESSED,
    UP_PRESSED,
    DOWN_PRESSED,
    UP_UNPRESSED,
    DOWN_UNPRESSED,
};

#endif // __EVENTS_ENUM_H__